# Generated by Django 2.2.2 on 2019-07-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_adventure_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='tier',
            field=models.CharField(blank=True, choices=[('tier1', 'Tier 1'), ('tier2', 'Tier 2'), ('tier3', 'Tier 3'), ('tier4', 'Tier 4')], max_length=6, null=True, verbose_name='Tier'),
        ),
    ]
