# Generated by Django 2.2.9 on 2020-11-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_table_extra_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='virtual',
            field=models.BooleanField(default=False, verbose_name='Is only virtual'),
        ),
    ]
