# Generated by Django 2.2.13 on 2020-10-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0014_table_extra_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="report_notes",
            field=models.TextField(blank=True, verbose_name="Extra report notes"),
        ),
    ]
