# Generated by Django 2.2.9 on 2020-02-01 20:55

from django.db import migrations, models


def add_online_table(apps, schema_editor):
    Table = app.get_model("games", "Table")

    try:
        Table.objects.get(name="Online")
    except Table.DoesNotExist:
        Table.objects.create(
            name="Online",
            max_spots=7,
        )


class Migration(migrations.Migration):

    dependencies = [("games", "0014_table_extra_notes")]

    operations = [
        migrations.RunPython(add_online_table)
    ]
